FROM public.ecr.aws/sam/build-python3.8:latest

# Update environment
RUN yum update -y

# Install docker
RUN yum install -y amazon-linux-extras
RUN PYTHON=python2 amazon-linux-extras install docker

# Install poetry
RUN pip install poetry==1.4.2
RUN poetry config virtualenvs.in-project true

# Install nodejs 14.x and yarn
RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash -
RUN yum install -y nodejs
RUN npm install -g yarn

# Compatible with initial base image
ENTRYPOINT []
CMD ["/bin/bash"]
